
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '9E5FF35E5203BF8B53A16C9E33FDFD3F'
    
_lr_action_items = {'NETWORK':([0,],[1,]),'WORD':([1,8,12,15,18,21,33,44,45,59,62,],[4,15,15,-9,23,15,44,-13,44,44,44,]),'RINDEX':([51,],[57,]),'PROPERTY':([10,23,29,34,35,36,38,40,54,56,60,],[18,-31,18,-19,-20,18,-21,-22,-26,-27,-23,]),'LPAREN':([5,23,29,34,35,36,38,40,54,56,60,],[12,-31,33,-19,-20,33,-21,-22,-26,-27,-23,]),'SEMI':([47,48,49,50,55,58,63,],[54,-30,-28,56,-29,60,65,]),'PROBABILITY':([2,6,7,11,17,24,30,42,],[5,5,5,-2,-3,-4,-8,-14,]),'DECIMAL':([41,],[51,]),'LINDEX':([31,],[41,]),'DISCRETE':([28,],[31,]),'$end':([2,3,6,7,9,11,13,14,17,24,30,42,],[-5,0,-5,-5,-1,-2,-6,-7,-3,-4,-8,-14,]),'TABLEVALUES':([23,29,34,35,36,38,40,54,56,60,],[-31,39,-19,-20,39,-21,-22,-26,-27,-23,]),'RPAREN':([15,20,21,26,43,44,45,53,],[-9,25,-15,-16,52,-13,-24,-25,]),'VARIABLETYPE':([22,],[28,]),'VARIABLE':([2,6,7,11,17,24,30,42,],[8,8,8,-2,-3,-4,-8,-14,]),'DEFAULTVALUE':([23,29,34,35,36,38,40,54,56,60,],[-31,37,-19,-20,37,-21,-22,-26,-27,-23,]),'LBRAC':([4,15,16,25,57,],[10,-9,22,29,59,]),'NUMBER':([37,39,48,49,52,],[48,48,-30,48,48,]),'RBRAC':([10,19,23,27,29,32,34,35,36,38,40,44,46,54,56,59,60,61,62,64,65,],[17,24,-31,30,-17,42,-19,-20,-17,-21,-22,-13,-18,-26,-27,-11,-23,63,-11,-12,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'VariableValuesList':([59,62,],[61,64,]),'ProbabilityVariableName':([8,12,21,],[16,21,21,]),'FloatingPointList':([37,39,49,52,],[47,50,55,58,]),'FloatingPointToken':([37,39,49,52,],[49,49,49,49,]),'ProbabilityVariablesList':([12,21,],[20,26,]),'ProbabilityContentList':([29,36,],[32,46,]),'VariableDeclaration':([2,6,7,],[6,6,6,]),'ProbabilityDeclaration':([2,6,7,],[7,7,7,]),'PropertyValue':([10,29,36,],[19,34,34,]),'ProbabilityDefaultEntry':([29,36,],[35,35,]),'CompilationUnit':([0,],[3,]),'VariableDiscrete':([22,],[27,]),'ProbabilityContent':([29,36,],[36,36,]),'CompilationContent':([2,6,7,],[9,13,14,]),'ProbabilityValuesList':([33,45,],[43,53,]),'ProbabilityEntry':([29,36,],[38,38,]),'NetworkDeclaration':([0,],[2,]),'NetworkContent':([4,],[11,]),'ProbabilityVariableValue':([33,45,59,62,],[45,45,62,62,]),'ProbabilityTable':([29,36,],[40,40,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> CompilationUnit","S'",1,None,None,None),
  ('CompilationUnit -> NetworkDeclaration CompilationContent','CompilationUnit',2,'p_CompilationUnit','bifparser.py',112),
  ('NetworkDeclaration -> NETWORK WORD NetworkContent','NetworkDeclaration',3,'p_NetworkDeclaration','bifparser.py',130),
  ('NetworkContent -> LBRAC RBRAC','NetworkContent',2,'p_NetworkContent','bifparser.py',135),
  ('NetworkContent -> LBRAC PropertyValue RBRAC','NetworkContent',3,'p_NetworkContent','bifparser.py',136),
  ('CompilationContent -> <empty>','CompilationContent',0,'p_CompilationContent','bifparser.py',140),
  ('CompilationContent -> VariableDeclaration CompilationContent','CompilationContent',2,'p_CompilationContent','bifparser.py',141),
  ('CompilationContent -> ProbabilityDeclaration CompilationContent','CompilationContent',2,'p_CompilationContent','bifparser.py',142),
  ('VariableDeclaration -> VARIABLE ProbabilityVariableName LBRAC VariableDiscrete RBRAC','VariableDeclaration',5,'p_VariableDeclaration','bifparser.py',152),
  ('ProbabilityVariableName -> WORD','ProbabilityVariableName',1,'p_ProbabilityVariableName','bifparser.py',157),
  ('VariableDiscrete -> VARIABLETYPE DISCRETE LINDEX DECIMAL RINDEX LBRAC VariableValuesList RBRAC SEMI','VariableDiscrete',9,'p_VariableDiscrete','bifparser.py',161),
  ('VariableValuesList -> <empty>','VariableValuesList',0,'p_VariableValuesList','bifparser.py',165),
  ('VariableValuesList -> ProbabilityVariableValue VariableValuesList','VariableValuesList',2,'p_VariableValuesList','bifparser.py',166),
  ('ProbabilityVariableValue -> WORD','ProbabilityVariableValue',1,'p_ProbabilityVariableValue','bifparser.py',174),
  ('ProbabilityDeclaration -> PROBABILITY LPAREN ProbabilityVariablesList RPAREN LBRAC ProbabilityContentList RBRAC','ProbabilityDeclaration',7,'p_ProbabilityDeclaration','bifparser.py',178),
  ('ProbabilityVariablesList -> ProbabilityVariableName','ProbabilityVariablesList',1,'p_ProbabilityVariablesList','bifparser.py',189),
  ('ProbabilityVariablesList -> ProbabilityVariableName ProbabilityVariablesList','ProbabilityVariablesList',2,'p_ProbabilityVariablesList','bifparser.py',190),
  ('ProbabilityContentList -> <empty>','ProbabilityContentList',0,'p_ProbabilityContentList','bifparser.py',198),
  ('ProbabilityContentList -> ProbabilityContent ProbabilityContentList','ProbabilityContentList',2,'p_ProbabilityContentList','bifparser.py',199),
  ('ProbabilityContent -> PropertyValue','ProbabilityContent',1,'p_ProbabilityContent','bifparser.py',207),
  ('ProbabilityContent -> ProbabilityDefaultEntry','ProbabilityContent',1,'p_ProbabilityContent','bifparser.py',208),
  ('ProbabilityContent -> ProbabilityEntry','ProbabilityContent',1,'p_ProbabilityContent','bifparser.py',209),
  ('ProbabilityContent -> ProbabilityTable','ProbabilityContent',1,'p_ProbabilityContent','bifparser.py',210),
  ('ProbabilityEntry -> LPAREN ProbabilityValuesList RPAREN FloatingPointList SEMI','ProbabilityEntry',5,'p_ProbabilityEntry','bifparser.py',214),
  ('ProbabilityValuesList -> ProbabilityVariableValue','ProbabilityValuesList',1,'p_ProbabilityValuesList','bifparser.py',218),
  ('ProbabilityValuesList -> ProbabilityVariableValue ProbabilityValuesList','ProbabilityValuesList',2,'p_ProbabilityValuesList','bifparser.py',219),
  ('ProbabilityDefaultEntry -> DEFAULTVALUE FloatingPointList SEMI','ProbabilityDefaultEntry',3,'p_ProbabilityDefaultEntry','bifparser.py',227),
  ('ProbabilityTable -> TABLEVALUES FloatingPointList SEMI','ProbabilityTable',3,'p_ProbabilityTable','bifparser.py',231),
  ('FloatingPointList -> FloatingPointToken','FloatingPointList',1,'p_FloatingPointList','bifparser.py',235),
  ('FloatingPointList -> FloatingPointToken FloatingPointList','FloatingPointList',2,'p_FloatingPointList','bifparser.py',236),
  ('FloatingPointToken -> NUMBER','FloatingPointToken',1,'p_FloatingPointToken','bifparser.py',244),
  ('PropertyValue -> PROPERTY WORD','PropertyValue',2,'p_PropertyValue','bifparser.py',248),
]
